version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - L3tum
  labels:
  - bug
  ignore:
  - dependency-name: HtmlAgilityPack
    versions:
    - 1.11.30
    - 1.11.31
    - 1.11.32
