name: Docs

on:
  repository_dispatch:
    types: [docs-command]
  schedule:
    - cron: 0 */12 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Clone website repo
      run: |
        rm -rf docs
        mkdir -p docs
        cd docs
        git clone https://github.com/L3tum/CPU-Benchmark-Website.git
        cd CPU-Benchmark-Website
    - name: Move website to docs
      run: |
        cp docs/CPU-Benchmark-Website/dist/* docs/
        cp docs/CPU-Benchmark-Website/VERSION docs/VERSION
        rm -rf docs/CPU-Benchmark-Website
    - name: push back
      shell: bash
      run: |
          git config --global user.name 'L3tum'
          git config --global user.email 'l3tum@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git add -A
          git commit -am "Updated docs"
          git push
        
