name: Release

on: 
  release:

jobs:
  release-zips:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet 3.0.1
      run: ./build.ps1 -v "${{ github.event.release.tag_name }}"
      shell: pwsh
    - uses: JasonEtco/upload-to-release@master
      with:
        args: Benchmarker/bin/Release/ZIPs/Benchmarker.zip application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: JasonEtco/upload-to-release@master
      with:
        args: Benchmarker/bin/Release/ZIPs/Benchmarker-win64.zip application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: JasonEtco/upload-to-release@master
      with:
        args: Benchmarker/bin/Release/ZIPs/Benchmarker-win32.zip application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: JasonEtco/upload-to-release@master
      with:
        args: Benchmarker/bin/Release/ZIPs/Benchmarker-linux-arm32v7.zip application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: JasonEtco/upload-to-release@master
      with:
        args: Benchmarker/bin/Release/ZIPs/Benchmarker-win-arm32v7.zip application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: JasonEtco/upload-to-release@master
      with:
        args: Benchmarker/bin/Release/ZIPs/Benchmarker-win-arm64.zip application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: JasonEtco/upload-to-release@master
      with:
        args: Benchmarker/bin/Release/ZIPs/Benchmarker-linux64.zip application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: JasonEtco/upload-to-release@master
      with:
        args: Benchmarker/bin/Release/ZIPs/Benchmarker-debian64.zip application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: JasonEtco/upload-to-release@master
      with:
        args: Benchmarker/bin/Release/ZIPs/Benchmarker-ubuntu64.zip application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: JasonEtco/upload-to-release@master
      with:
        args: Benchmarker/bin/Release/ZIPs/Benchmarker-osx64.zip application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  release-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Run Buildx for version ${{ github.event.release.tag_name }}
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} && \
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --output "type=image,push=true" \
            --tag l3tum/rial-bench:${{ github.event.release.tag_name }} \
            --build-arg BUILD_VERSION="${{ github.event.release.tag_name }}" \
            --file ./Dockerfile .
      - name: Run Buildx for version latest
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} && \
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --output "type=image,push=true" \
            --tag l3tum/rial-bench:latest \
            --build-arg BUILD_VERSION="${{ github.event.release.tag_name }}" \
            --file ./Dockerfile .
